baseurl: # the subpath of your site, e.g. /blog
url: "https://jalvarezga.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
baseurl: # the subpath of your site, e.g. /blog
url: "https://jalvarezga.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-slate # (or whatever theme you're using)
sass:
  sass_dir: _sass
  style: compressed

# Pagination settings
paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

