#-------------------------------
# General Site Settings
title: Joaquin Alvarez
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Joaquin Alvarez
  image: profile_pic.jpg
  say-hello: Joaquin Alvarez
  bio:  I obtained my Bachelor's degree in Applied Mathematics at ITAM in Mexico City. I've been fortunate to receive guidance and mentorship from professors Miguel Angel Mota, Mauricio Romero and Edgar Francisco Roman-Rangel. I am interested in distribution-free uncertainty quantification to guarantee the safe deployment of machine learning models in high-risk settings. My curiosity is captivated by the uncertainty that naturally arises in diverse fields of machine leraning such as computer vision, autonomous AI systems, or large language models. I aspire to build rigorous cutting-edge statistical tools to deploy black-box models in an efficient and reliable manner. Currently I am applying to PhD programs to take my research to the next level. Feel free to reach out and check my research.
 


#-------------------------------
# Contact links
twitter: https://x.com/artisticML # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
googlescholar: https://scholar.google.com/citations?hl=en&user=9D0eWhgAAAAJ
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------


#-------------------------------
# Instagram Feed
#instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
#instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
#google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
